# Generated by Django 5.0.6 on 2024-05-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField()),
                ('tg_name', models.CharField(max_length=1024)),
                ('joined_to_chanel', models.BooleanField(default=False)),
                ('winner', models.BooleanField(default=False)),
            ],
        ),
    ]
