# Generated by Django 5.0.6 on 2024-06-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawusers',
            name='sex',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
    ]
